### ISSUE TITLE
[>=0.9.0] testrunner crashes when compiled with -DNDEBUG

### ISSUE THREAD

**Issue by hartwork** [uriparser/uriparser#67]
```
# gdb -batch -ex run -ex bt --args ./testrunner
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[==========] Running 90 tests from 11 test cases.
[----------] Global test environment set-up.
[----------] 7 tests from FourSuite
[ RUN      ] FourSuite.AbsolutizeTestCases
[       OK ] FourSuite.AbsolutizeTestCases (1 ms)
[ RUN      ] FourSuite.RelativizeTestCases
[       OK ] FourSuite.RelativizeTestCases (0 ms)
[ RUN      ] FourSuite.GoodUriReferences
[       OK ] FourSuite.GoodUriReferences (0 ms)
[ RUN      ] FourSuite.BadUriReferences
[       OK ] FourSuite.BadUriReferences (0 ms)
[ RUN      ] FourSuite.CaseNormalizationTests
[       OK ] FourSuite.CaseNormalizationTests (0 ms)
[ RUN      ] FourSuite.PctEncNormalizationTests
[       OK ] FourSuite.PctEncNormalizationTests (0 ms)
[ RUN      ] FourSuite.PathSegmentNormalizationTests
[       OK ] FourSuite.PathSegmentNormalizationTests (0 ms)
[----------] 7 tests from FourSuite (1 ms total)

[----------] 2 tests from MemoryManagerCompletenessSuite
[ RUN      ] MemoryManagerCompletenessSuite.AllFunctionMembersRequired
munmap_chunk(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff7a18b1b in raise () from /lib64/libc.so.6
#0  0x00007ffff7a18b1b in raise () from /lib64/libc.so.6
#1  0x00007ffff7a02535 in abort () from /lib64/libc.so.6
#2  0x00007ffff7a5e699 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff7a664a8 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff7a667f4 in munmap_chunk () from /lib64/libc.so.6
#5  0x00005555555cea17 in uriDefaultFree ()
#6  0x00005555555d56e8 in uriFreeUriMembersMmA ()
#7  0x000055555557cea2 in MemoryManagerCompletenessSuite_AllFunctionMembersRequired_Test::TestBody() ()
#8  0x00007ffff7f617fa in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) () from /usr/lib64/libgtest.so
#9  0x00007ffff7f56bba in testing::Test::Run() () from /usr/lib64/libgtest.so
#10 0x00007ffff7f56d08 in testing::TestInfo::Run() () from /usr/lib64/libgtest.so
#11 0x00007ffff7f56de5 in testing::TestCase::Run() () from /usr/lib64/libgtest.so
#12 0x00007ffff7f5729c in testing::internal::UnitTestImpl::RunAllTests() () from /usr/lib64/libgtest.so
#13 0x00007ffff7f61d0a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) () from /usr/lib64/libgtest.so
#14 0x00007ffff7f57448 in testing::UnitTest::Run() () from /usr/lib64/libgtest.so
#15 0x00005555555c34d7 in RUN_ALL_TESTS() ()
#16 0x00005555555bf36d in main ()
```

**Comment by veprbl** [comment]
Would be nice to have a release with this fix!

**Comment by hartwork** [comment]
@veprbl there is a release 0.9.4 at https://github.com/uriparser/uriparser/releases now.
